In [98]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
df = pd.read_csv('./data/train.csv', sep='|')
df_test = pd.read_csv('./data/test.csv', sep='|')

new_df = df.dropna()
new_df_test = df_test.dropna()

new_df.insert(1, 'totalItemsScanned', new_df['scannedLineItemsPerSecond'] * new_df['totalScanTimeInSeconds'])
new_df_test.insert(1, 'totalItemsScanned', new_df_test['scannedLineItemsPerSecond'] * new_df_test['totalScanTimeInSeconds'])

y_train = new_df.pop('fraud')

X_train = new_df.drop(columns=[
    'scannedLineItemsPerSecond', 'lineItemVoidsPerPosition', 'valuePerSecond',
    'quantityModifications', 'grandTotal'
])
X_test = new_df_test.drop(columns=[
    'scannedLineItemsPerSecond', 'lineItemVoidsPerPosition', 'valuePerSecond',
    'quantityModifications', 'grandTotal'
])

print('Labels counts in X_train',len(X_train))

Labels counts in X_train 1879


In [99]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)

In [100]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression


# Dự đoán kết quả từng mô hình và lưu vào DataFrame
# Decision Tree
dt_model = DecisionTreeClassifier(max_depth=3, criterion='gini')
dt_model.fit(X_train, y_train)
dt_preds_train = dt_model.predict(X_train)
dt_preds_val = dt_model.predict(X_val)

# K-Nearest Neighbors
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
knn_preds_train = knn_model.predict(X_train)
knn_preds_val = knn_model.predict(X_val)

# Logistic Regression
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_preds_train = lr_model.predict(X_train)
lr_preds_val = lr_model.predict(X_val)

c:\Users\dabei-laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


**Đánh giá hiệu suất**

In [101]:
import sklearn.metrics as metrics

dt_train_cm = metrics.confusion_matrix(y_train, dt_preds_train)
dt_train_accuracy = metrics.accuracy_score(y_train,dt_preds_train)
print('The train confusion matrix for Decision Tree model is:', '\n', dt_train_cm)

dt_val_cm = metrics.confusion_matrix(y_val,dt_preds_val)
dt_val_accuracy = metrics.accuracy_score(y_val,dt_preds_val)
print('The validation confusion matrix for Decision Tree model is:', '\n', dt_val_cm)

print('Train accuracy: ',dt_train_accuracy,' | Validation accuracy: ',dt_val_accuracy)


The train confusion matrix for Decision Tree model is: 
 [[1416    6]
 [  29   52]]
The validation confusion matrix for Decision Tree model is: 
 [[351   2]
 [  6  17]]
Train accuracy:  0.9767132401862941  | Validation accuracy:  0.9787234042553191


In [102]:
knn_train_cm = metrics.confusion_matrix(y_train, knn_preds_train)
knn_train_accuracy = metrics.accuracy_score(y_train,knn_preds_train)
print('The train confusion matrix for K-NN model is:', '\n', knn_train_cm)

knn_val_cm = metrics.confusion_matrix(y_val,knn_preds_val)
knn_val_accuracy = metrics.accuracy_score(y_val,knn_preds_val)
print('The validation confusion matrix for K-NN model is:', '\n', knn_val_cm)

print('Train accuracy: ',knn_train_accuracy,' | Validation accuracy: ',knn_val_accuracy)



The train confusion matrix for K-NN model is: 
 [[1418    4]
 [  74    7]]
The validation confusion matrix for K-NN model is: 
 [[349   4]
 [ 23   0]]
Train accuracy:  0.9481037924151696  | Validation accuracy:  0.9281914893617021


In [103]:
lr_train_cm = metrics.confusion_matrix(y_train, lr_preds_train)
lr_train_accuracy = metrics.accuracy_score(y_train,lr_preds_train)
print('The train confusion matrix for Logistic Regression model is:', '\n', lr_train_cm)

lr_val_cm = metrics.confusion_matrix(y_val,lr_preds_val)
lr_val_accuracy = metrics.accuracy_score(y_val,lr_preds_val)
print('The validation confusion matrix for Logistic Regression model is:', '\n', lr_train_cm)

print('Train accuracy: ',lr_train_accuracy,' | Validation accuracy: ',lr_val_accuracy)


The train confusion matrix for Logistic Regression model is: 
 [[1417    5]
 [   5   76]]
The validation confusion matrix for Logistic Regression model is: 
 [[1417    5]
 [   5   76]]
Train accuracy:  0.9933466400532269  | Validation accuracy:  0.9920212765957447


In [104]:
# import matplotlib.pyplot as plt
# from sklearn.tree import plot_tree

# plt.figure(figsize=(30, 20))

# # Vẽ cây quyết định
# plot_tree(dt_model, feature_names=X_train.columns, class_names=['No', 'Yes'], filled=True)

# plt.show()

In [105]:
lr_pred_test = lr_model.predict(X_test)

# Create result DataFrame
result_df = pd.DataFrame({"Logistic_Regression fraud predict": lr_pred_test})

# Lưu kết quả ra file CSV
result_df.to_csv("./result/result.csv", index=False)